In [1]:
# !pip3 install torch torchvision torchaudio

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0


### Intro to Tensors

#### Creating tensors

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim, scalar.item()

(0, 7)

In [5]:
# vector
vector = torch.tensor([7, 8, 9])
vector

tensor([7, 8, 9])

In [6]:
vector.ndim, vector.shape, vector.size()

(1, torch.Size([3]), torch.Size([3]))

In [7]:
# matrix
matrix = torch.tensor([[7, 8, 9], [10, 11, 12]])
matrix

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [8]:
matrix.ndim, matrix.shape, matrix.size()

(2, torch.Size([2, 3]), torch.Size([2, 3]))

In [9]:
# tensor
tensor = torch.tensor([[[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
tensor

tensor([[[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]])

In [10]:
tensor.ndim, tensor.shape, tensor.size()

(3, torch.Size([2, 2, 3]), torch.Size([2, 2, 3]))

#### Random tensors

`torch.rand`: https://pytorch.org/docs/stable/generated/torch.rand.html#torch-rand

In [11]:
# create a random tensor of size(3, 4)
random_tensor = torch.rand(3, 4)
random_tensor 

tensor([[0.4238, 0.7447, 0.4036, 0.4850],
        [0.3125, 0.5325, 0.4670, 0.7299],
        [0.4134, 0.2969, 0.9016, 0.8870]])

In [12]:
random_tensor.ndim, random_tensor.shape, random_tensor.size()

(2, torch.Size([3, 4]), torch.Size([3, 4]))

In [13]:
random_tensor_2 = torch.rand(1, 3, 4)
random_tensor_2

tensor([[[0.1927, 0.5567, 0.5487, 0.4139],
         [0.2279, 0.7176, 0.3426, 0.1769],
         [0.7305, 0.9845, 0.1790, 0.3923]]])

In [14]:
random_image_tensor = torch.rand(3, 224, 224)
random_image_tensor

tensor([[[0.8149, 0.1677, 0.4351,  ..., 0.9927, 0.0644, 0.4225],
         [0.1129, 0.7381, 0.5124,  ..., 0.6110, 0.9773, 0.9841],
         [0.0305, 0.3248, 0.7526,  ..., 0.2889, 0.1209, 0.4713],
         ...,
         [0.8875, 0.0599, 0.2724,  ..., 0.6260, 0.1820, 0.9112],
         [0.0353, 0.9849, 0.3606,  ..., 0.9512, 0.9758, 0.5076],
         [0.8600, 0.5796, 0.6520,  ..., 0.6255, 0.9592, 0.4960]],

        [[0.2404, 0.0503, 0.5371,  ..., 0.2416, 0.9866, 0.3476],
         [0.1004, 0.5664, 0.9564,  ..., 0.6528, 0.5918, 0.9035],
         [0.7210, 0.7986, 0.9822,  ..., 0.4682, 0.5773, 0.6912],
         ...,
         [0.1282, 0.0106, 0.9466,  ..., 0.2811, 0.0421, 0.8800],
         [0.1412, 0.5753, 0.9820,  ..., 0.0386, 0.4786, 0.9215],
         [0.0962, 0.2681, 0.3254,  ..., 0.8193, 0.6791, 0.6248]],

        [[0.3801, 0.7340, 0.0815,  ..., 0.8120, 0.4332, 0.6213],
         [0.6396, 0.1594, 0.6907,  ..., 0.3741, 0.3144, 0.3106],
         [0.0165, 0.4216, 0.4714,  ..., 0.0461, 0.6073, 0.

In [15]:
# create zeros and ones
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [16]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
ones.dtype

torch.float32

#### Range tensors and tensor likes

`torch.arange`: https://pytorch.org/docs/stable/generated/torch.arange.html#torch-arange

In [18]:
# create a range of numbers
# torch.range(0, 10)
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# creating tensors like
tensor_ones = torch.ones_like(random_image_tensor)
tensor_ones

tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]]])

In [20]:
tensor_zeros = torch.zeros_like(random_image_tensor)
tensor_zeros

tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])

#### Tensor datatypes
- Three common errors:
    - Tensors not right type (type errors). Check with `tensor.dtype`.
    - Tensors not right shape (shape errors). Check with `tensor.shape` or `tensor.size()`.
    - Tensors not on the right device (device errors). Check with `tensor.device`.

#### Tensor Operations
1. Addition
2. Subtraction
3. Multiplication (element-wise, matrix multiplication)
4. Division

In [21]:
t = torch.tensor([1, 2, 3])
print(t + 10)
print(t - 10)
print(t * 10)
print(t / 10)

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])


In [22]:
torch.add(t, 10), torch.mul(t, 10), torch.div(t, 10), torch.sub(t, 10)

(tensor([11, 12, 13]),
 tensor([10, 20, 30]),
 tensor([0.1000, 0.2000, 0.3000]),
 tensor([-9, -8, -7]))

In [23]:
# tensor multiplication
# element-wise multiplication
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t1 * t2

tensor([ 4, 10, 18])

In [ ]:
# matrix multiplication
torch.matmul(t1, t2)

tensor(32)

In [ ]:
t1 @ t2 # alt

tensor(32)

In [28]:
# transpose
t1 = torch.tensor([[1, 2, 5], [3, 4, 3]])
t2 = torch.tensor([[5, 1, 6], [2, 7, 8]])
t1.shape, t2.shape

(torch.Size([2, 3]), torch.Size([2, 3]))

In [29]:
t1.T @ t2

tensor([[11, 22, 30],
        [18, 30, 44],
        [31, 26, 54]])

In [30]:
(t1.T @ t2).shape

torch.Size([3, 3])

#### Tensor aggregation

In [32]:
x = torch.arange(0, 100, 10)

In [33]:
torch.min(x), x.min(), x.max(), torch.max(x), x.argmax(), x.argmin()

(tensor(0), tensor(0), tensor(90), tensor(90), tensor(9), tensor(0))

In [36]:
# torch.mean(x) # mean is not defined for integer tensors
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [37]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [39]:
torch.std(x.type(torch.float32)), x.type(torch.float32).std(), torch.var(x.type(torch.float32)), x.type(torch.float32).var()

(tensor(30.2765), tensor(30.2765), tensor(916.6667), tensor(916.6667))

#### Reshape, View and Stack Tensors

In [48]:
x = torch.arange(1., 10.)

In [49]:
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [50]:
# x_reshaped = x.reshape(1, 7) # 1 row, 7 columns won't work.
x_reshaped = x.reshape(1, 9) # valid shape
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [51]:
x_reshaped = x.reshape(3, 3) # 3 rows, 3 columns
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [52]:
# change the view
z = x.view(1, 9) # shares the same memory as x
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [53]:
z[0,:2] = 100
x, z

(tensor([100., 100.,   3.,   4.,   5.,   6.,   7.,   8.,   9.]),
 tensor([[100., 100.,   3.,   4.,   5.,   6.,   7.,   8.,   9.]]))

In [56]:
x_stacked = torch.stack([z, z, z], dim=0) # stack along the first dimension
x_stacked, x_stacked.shape

(tensor([[[100., 100.,   3.,   4.,   5.,   6.,   7.,   8.,   9.]],
 
         [[100., 100.,   3.,   4.,   5.,   6.,   7.,   8.,   9.]],
 
         [[100., 100.,   3.,   4.,   5.,   6.,   7.,   8.,   9.]]]),
 torch.Size([3, 1, 9]))

In [57]:
x_stacked = torch.stack([z, z, z], dim=1) # stack along the second dimension
x_stacked, x_stacked.shape

(tensor([[[100., 100.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
          [100., 100.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
          [100., 100.,   3.,   4.,   5.,   6.,   7.,   8.,   9.]]]),
 torch.Size([1, 3, 9]))

In [58]:
x_vstacked = torch.vstack([z, z, z]) # stack along the first dimension
x_vstacked, x_vstacked.shape

(tensor([[100., 100.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
         [100., 100.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
         [100., 100.,   3.,   4.,   5.,   6.,   7.,   8.,   9.]]),
 torch.Size([3, 9]))

In [59]:
x_hstacked = torch.hstack([z, z, z]) # stack along the second dimension
x_hstacked, x_hstacked.shape

(tensor([[100., 100.,   3.,   4.,   5.,   6.,   7.,   8.,   9., 100., 100.,   3.,
            4.,   5.,   6.,   7.,   8.,   9., 100., 100.,   3.,   4.,   5.,   6.,
            7.,   8.,   9.]]),
 torch.Size([1, 27]))

In [60]:
a = torch.tensor([[1, 2]])
b = torch.tensor([[3, 4]])

torch.hstack((a, b))

tensor([[1, 2, 3, 4]])

#### Squeeze and Unsqueeze Tensors

In [ ]:
x_reshaped.shape, x_reshaped.squeeze().shape # squeeze removes all dimensions of size 1, none here

(torch.Size([3, 3]), torch.Size([3, 3]))

In [62]:
z.shape, z.squeeze().shape

(torch.Size([1, 9]), torch.Size([9]))

In [65]:
x_reshaped.unsqueeze(dim=0).shape # unsqueeze adds a dimension of size 1


torch.Size([1, 3, 3])

In [67]:
z.unsqueeze(dim=0).shape, z.unsqueeze(dim=1).shape, z.unsqueeze(dim=-1).shape

(torch.Size([1, 1, 9]), torch.Size([1, 1, 9]), torch.Size([1, 9, 1]))

In [ ]:
z.shape, torch.permute(z, (1, 0)).shape # swap the first and second dimensions; IT'S A VIEW!


(torch.Size([1, 9]), torch.Size([9, 1]))

In [70]:
img = torch.rand(3, 224, 224)
img.shape, img.permute(1, 2, 0).shape # swap the first and second dimensions

(torch.Size([3, 224, 224]), torch.Size([224, 224, 3]))

In [ ]:
assert img[1, 0, 0] == img.permute(1, 2, 0)[0, 0, 1]

- `.from_numpy()` and `.numpy()` functions are handy to interchange between Npy and PyT. (Note: Numpy tensors do not work on GPU)
- `torch.manual_seed(<some number>)` for reproducibility.
- `torch.cuda.is_available()` to check GPU availability.