### Appendix-A
Source: Machine Learning with PyTorch and Scikit-Learn - Sebastian Raschka

In [1]:
import torch
torch.cuda.is_available()

False

In [2]:
print(torch.backends.mps.is_available()) # check if Apple M1 supports acceleration.

True


In [3]:
tensor0d = torch.tensor(1)     #1

In [7]:
tensor0d.shape

torch.Size([])

In [5]:
tensor1d = torch.tensor([1, 2, 3])    #2

In [8]:
tensor1d.shape

torch.Size([3])

In [9]:
tensor2d = torch.tensor([[1, 2], 
                         [3, 4]])     #3

In [10]:
tensor2d.shape

torch.Size([2, 2])

In [11]:
tensor3d = torch.tensor([[[1, 2], [3, 4]], 
                         [[5, 6], [7, 8]]])    #4

In [12]:
tensor3d.shape

torch.Size([2, 2, 2])

In [13]:
tensor1d.dtype

torch.int64

In [14]:
tensor3d.dtype

torch.int64

In [15]:
floatvec = torch.tensor([1.0, 2.0, 3.0])
print(floatvec.dtype)

torch.float32


In [16]:
print(tensor3d.reshape(4, 2, 1))

tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]],

        [[7],
         [8]]])


In [17]:
print(tensor2d.view(4, 1))

tensor([[1],
        [2],
        [3],
        [4]])


In [18]:
print(tensor2d.T)

tensor([[1, 3],
        [2, 4]])


In [19]:
print(tensor2d)

tensor([[1, 2],
        [3, 4]])


In [20]:
print(tensor2d.matmul(tensor2d.T))


tensor([[ 5, 11],
        [11, 25]])


In [21]:
print(tensor2d @ tensor2d.T)

tensor([[ 5, 11],
        [11, 25]])


In [ ]:
class NeuralNetExample(torch.nn.Module):
    def __init__(self, num_inputs, num_outputs):
        super().__init__()
        
        self.layers = torch.nn.Sequential(
            torch.nn.Linear(num_inputs, 30),
            torch.nn.ReLU(),

            torch.nn.Linear(30, 20),
            torch.nn.ReLU()

            torch.nn.Linear(20, num_outputs)
        )
    
    def forward(self, x):
        logits = self.layers(x)
        return logits


In [ ]:
m = NeuralNetExample(50, 3)
print(m)